language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script: composer install --dev --prefer-source

notifications:
  email: "douglas@usemarkup.com"

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
